---
title: "Abbreviated SST-ID - Data preparation - DeNoPa"
author: "Juan Li"
date: "2024-02-28"
output:  
  bookdown::html_document2:
    toc: true
    number_sections: true
    toc_float: true
    fig_caption: yes
    global_numbering: true 
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width=8
)
```

# Load packages

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
```

# DeNoPa

## read in all data

```{r, echo=FALSE, message=FALSE, warning=FALSE}
data_path  <- "/Users/juan/Desktop/OHRI/work/Cohorts/!DeNoPa PPMI Temporal/DeNoPa"

data_BL  <- read.csv(paste(data_path, "/", "DeNoPa_Baseline_curated.csv",sep=""),header = T, fileEncoding="latin1", check.names=FALSE, na.strings=c("",".","NA"))
data_BL_2 <- read.csv(paste(data_path, "/", "Denopa - BL data.csv",sep=""),header = T,  fileEncoding="latin1", check.names=FALSE, na.strings=c("",".","NA"))

data_48  <- read.csv(paste(data_path, "/", "DeNoPa_48months_curated.csv",sep=""),header = T,  fileEncoding="latin1", check.names=FALSE, na.strings=c("",".","NA"))
data_48_2  <- read.csv(paste(data_path, "/", "PD_HC_V3_48FU.csv",sep=""),header = T, fileEncoding="latin1", check.names=FALSE, na.strings=c("",".","NA")) # only contains SST data

data_72  <- read.csv(paste(data_path, "/", "PD_HC_V4_72FU.csv",sep=""),header = T,  fileEncoding="latin1", check.names=FALSE, na.strings=c("",".","NA"))

data_120 <- read.csv(paste(data_path, "/", "PD_HC_V6_120FU.csv",sep=""),header = T, fileEncoding="latin1", check.names=FALSE, na.strings=c("",".","NA")) # contains the final diagnosis

diagnosis_note <- read.csv(paste(data_path, "/", "OND and RBD convert note.csv",sep=""),header = T)

data_V   <- read.csv("DeNoPa_variables.csv", header = T, na.strings=c("",".","NA"))
```

## select variables

```{r}
df_BL <- data_BL %>% 
  left_join(data_BL_2, 
            by = c("Patient ID"="﻿Probanden_Nr"))
  
df_BL  <- df_BL[,data_V[which(data_V[,2] %in% names(df_BL)),2]] # reorder by column name
names(df_BL) <- data_V[which(data_V[,2] %in% names(df_BL)),1]# update variable names
df_BL <- df_BL %>% 
  mutate(EVENT_ID = "baseline",
         month = 0,
         PD.NMS.02 = as.factor(PD.NMS.02))
```

```{r}
df_48 <- data_48 %>% 
  left_join(data_48_2, 
            by = c("Patient ID"="Probanden_Nr"))
df_48  <- df_48[,data_V[which(data_V[,3] %in% names(df_48)),3]] # reorder by column name
names(df_48) <- data_V[which(data_V[,3] %in% names(df_48)),1]# update variable names
df_48 <- df_48 %>% 
  mutate(EVENT_ID = "48FU",
         month = 48,
         PD.NMS.02 = as.factor(PD.NMS.02)) 
```

```{r}
df_72  <- data_72[,data_V[which(data_V[,4] %in% names(data_72)),4]] # reorder by column name
names(df_72) <- data_V[which(data_V[,4] %in% names(df_72)),1]# update variable names
df_72 <- df_72 %>% 
  mutate(EVENT_ID = "72FU",
         month = 72,
         sex = ifelse(is.na(sex), NA, ifelse(sex == 0, "Male", "Female")),
         PD.NMS.02 = as.factor(ifelse(is.na(PD.NMS.02), NA, 
                                      ifelse(PD.NMS.02 == 0, "No", "Yes")))) 
```

```{r}
df_120  <- data_120[,data_V[which(data_V[,5] %in% names(data_120)),5]] # reorder by column name
names(df_120) <- data_V[which(data_V[,5] %in% names(df_120)),1]# update variable names

lost_vec <- list(c(0), # drop out at Baseline visit 
                 c(5:8, 99), # lost or died before 24 FU -V2 
                 c(9:14),   # 48 FU -V3
                 c(15:20),  # 72 FU -V4
                 c(21:26),  # 96 FU -V5
                 c(27:32))  # 120 FU -V6

df_120 <- df_120 %>% 
  mutate(last_month = case_when(
    group.final == 0 ~ NA, # drop out at Baseline visit, remove from data
    group.final %in% lost_vec[[2]] ~ 0, # lost or died before 24 FU -V2 
    group.final %in% lost_vec[[3]] ~ 24, # lost or died before 48 FU -V3 
    group.final %in% lost_vec[[4]] ~ 48, # lost or died before 72 FU -V4 
    group.final %in% lost_vec[[5]] ~ 72, # lost or died before 96 FU -V5 
    group.final %in% lost_vec[[6]] ~ 96, # lost or died before 120 FU -V6
    TRUE ~ 120 # still in study
  ))
```

## update diagnosis

```{r}
HC_vec <- c(2,6,8,10,12,16,18,22,24,28,30)
PD_vec <- c(1,5,7,9,11,15,17,21,23,27,29)
OND_vec <- c(3,99,13,14,19,20,25,26,31,32)

DeNoPa_group_name <- c("HC", "OND", "PD")

df_BL <- df_BL %>% left_join(df_120, by = "ID") %>% 
  mutate(
    group = case_when(
      group.final == 0 ~ "0 = drop out at Baseline visit",
      group.final %in% HC_vec ~ DeNoPa_group_name[1],
      group.final %in% OND_vec ~ DeNoPa_group_name[2],
      group.final %in% PD_vec ~ DeNoPa_group_name[3]),
    leave.Visit = ifelse(group.final == 0, 1, 0)) %>% 
  filter(group != "0 = drop out at Baseline visit", leave.Visit == 0) %>% 
  droplevels()

df_48 <- df_48 %>% left_join(df_120, by = "ID") %>% 
  mutate(
    group = case_when(
      group.final == 0 ~ "0 = drop out at Baseline visit",
      group.final %in% HC_vec ~ DeNoPa_group_name[1],
      group.final %in% OND_vec ~ DeNoPa_group_name[2],
      group.final %in% PD_vec ~ DeNoPa_group_name[3]),
    leave.Visit = ifelse(is.na(last_month) | last_month < 48, 1, 0))%>% 
  filter(group != "0 = drop out at Baseline visit", leave.Visit == 0) %>% 
  droplevels() 

df_72 <- df_72 %>% left_join(df_120, by = "ID") %>% 
  mutate(
    group = case_when(
      group.final == 0 ~ "0 = drop out at Baseline visit",
      group.final %in% HC_vec ~ DeNoPa_group_name[1],
      group.final %in% OND_vec ~ DeNoPa_group_name[2],
      group.final %in% PD_vec ~ DeNoPa_group_name[3]),
    leave.Visit = ifelse(is.na(last_month) | last_month < 72, 1, 0))%>%  
  filter(group != "0 = drop out at Baseline visit", leave.Visit == 0) %>% 
  droplevels() 
```

## combine and save datasets

```{r}
df_D <- bind_rows(df_BL, df_48, df_72)
```

## get OND diagnosis

Note the "OND and RBD convert note.csv" has been updated.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_D <- df_D %>% 
  left_join(diagnosis_note, by = "ID")
```

## calculate SST.ID score

```{r}
df_D$nMissing <- rowSums(is.na(df_D %>% select(SS.ID.01.B:SS.ID.16.B)))
table(df_D %>% select(EVENT_ID, nMissing))

# remove rows with 16 missing - see the next cell
#df_D <- df_D %>% filter(nMissing < 16) %>% droplevels() %>% select(-nMissing)

# impute other missings as 0s
ind_B <- which(grepl(".B", names(df_D)))
df_D[,ind_B][is.na(df_D[,ind_B])] <- 0

# calculate SST.ID score
df_D$SST.ID <- rowSums(df_D %>% select(SS.ID.01.B:SS.ID.16.B))
df_D$SST.ID[df_D$nMissing == 16] <- NA
table(df_D %>% select(EVENT_ID, SST.ID), useNA = "ifany")
```

```{r}
# find subjects who had no valid SST-ID score
ids2 <- df_D$ID[which(df_D$EVENT_ID == "baseline" & df_D$nMissing == 16)]

df_D %>% group_by(ID) %>% 
  summarise(count = n(),
            count_missing = sum(is.na(SST.ID))) %>% 
  filter(ID %in% ids2)
```

```{r}
# find subjects who had no valid SST-ID score
df <- df_D %>% group_by(ID) %>% 
  summarise(count = n(),
            count_missing = sum(is.na(SST.ID))) %>% 
  filter(count == count_missing) 

ids <- df$ID

df_D %>% filter(ID %in% unlist(ids)) %>% select(ID, group)

# remove subjects who had no valid SST-ID score
df_D <- df_D %>% filter(!(ID %in% unlist(ids))) %>% droplevels()
```




## Define olfaction

```{r}
df_D <- df_D %>%
  mutate(olfaction = case_when(
    # Female, <= 30
    sex == "Female" & age <= 30 & SST.ID <= 11   ~ "Reduced",
    sex == "Female" & age <= 30                  ~ "Normal",
    # Male, <= 30
    sex == "Male"   & age <= 30 & SST.ID <= 11 ~ "Reduced",
    sex == "Male"   & age <= 30                ~ "Normal",
    # Female, <= 40
    sex == "Female" & age <= 40 & SST.ID <= 12 ~ "Reduced",
    sex == "Female" & age <= 40                ~ "Normal",
    # Male, <= 40
    sex == "Male"   & age <= 40 & SST.ID <= 12 ~ "Reduced",
    sex == "Male"   & age <= 40                ~ "Normal",
    # Female, <= 50
    sex == "Female" & age <= 50 & SST.ID <= 11 ~ "Reduced",
    sex == "Female" & age <= 50                ~ "Normal",
    # Male, <= 50
    sex == "Male"   & age <= 50 & SST.ID <= 11 ~ "Reduced",
    sex == "Male"   & age <= 50                ~ "Normal",
    # Female, <= 60
    sex == "Female" & age <= 60 & SST.ID <= 11 ~ "Reduced",
    sex == "Female" & age <= 60                ~ "Normal",
    # Male, <= 60
    sex == "Male"   & age <= 60 & SST.ID <= 10 ~ "Reduced",
    sex == "Male"   & age <= 60                ~ "Normal",
    # Female, <= 70
    sex == "Female" & age <= 70 & SST.ID <= 10  ~ "Reduced",
    sex == "Female" & age <= 70                 ~ "Normal",
    # Male, <= 70
    sex == "Male"   & age <= 70 & SST.ID <= 9 ~ "Reduced",
    sex == "Male"   & age <= 70               ~ "Normal",
    # Female, <= 80
    sex == "Female" & age <= 80 & SST.ID <= 7 ~ "Reduced",
    sex == "Female" & age <= 80               ~ "Normal",
    # Male, <= 80
    sex == "Male"   & age <= 80 & SST.ID <= 7 ~ "Reduced",
    sex == "Male"   & age <= 80               ~ "Normal",
    # Female, over 80
    sex == "Female" & SST.ID <= 3.8 ~ "Reduced",
    sex == "Female"                 ~ "Normal",
    # Male, over 80
    sex == "Male"   & SST.ID <= 5    ~ "Reduced",
    sex == "Male"                    ~ "Normal"
  ))

df_D$olfaction[is.na(df_D$SST.ID)] <- NA
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
df_D <- df_D %>% select(-c(month, group.final, PD.NMS.02, leave.Visit))

# reorder columns
df_D <- df_D[, c("ID", "EVENT_ID", "group", "diagnosis","sex", "age", "ethnic", "disease.duration", "last_month",
                 "SS.ID.01.B", "SS.ID.02.B", "SS.ID.03.B", "SS.ID.04.B", "SS.ID.05.B", "SS.ID.06.B", "SS.ID.07.B", "SS.ID.08.B",
                 "SS.ID.09.B", "SS.ID.10.B", "SS.ID.11.B", "SS.ID.12.B", "SS.ID.13.B", "SS.ID.14.B", "SS.ID.15.B", "SS.ID.16.B",
                 "SS.ID.01.M", "SS.ID.02.M", "SS.ID.03.M", "SS.ID.04.M", "SS.ID.05.M", "SS.ID.06.M", "SS.ID.07.M", "SS.ID.08.M",
                 "SS.ID.09.M", "SS.ID.10.M", "SS.ID.11.M", "SS.ID.12.M", "SS.ID.13.M", "SS.ID.14.M", "SS.ID.15.M", "SS.ID.16.M",
                 "SST.ID", "SST.TH", "SST.DS", "olfaction", "nMissing")]
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
write.csv(df_D, file = "DeNoPa_cut.csv", row.names=FALSE)
```

```{r}

```


